import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import { AuthContextProvider } from './firebase/AuthContext';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Engima | AI&ML Club IITK',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
    <html lang="en">
      <Head>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
        
      </Head>
      <body className={`${inter.className} bg-design`}>
      <AuthContextProvider>
          {children}
        </AuthContextProvider>
        <script src="./login.js"></script>
      </body>
    </html>
  );
}
